# fly.toml app configuration file generated for is-there-a-game on 2023-11-26T14:56:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "is-there-a-game"
primary_region = "arn"

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
